name:                cooperstorage
version:             0.1.0.0
github:              "githubuser/cooperstorage"
license:             BSD3
author:              "Alex Drummond"
maintainer:          "a.d.drummond@gmail.com"
copyright:           "2018 Alex Drummond"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the blog post at <https://adrummond.net/posts/cooper>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

ghc-options: "-XDataKinds -XFlexibleContexts -XFlexibleInstances -XGADTs -XMultiParamTypeClasses -XNamedFieldPuns -XPolyKinds -XTypeFamilies -XFunctionalDependencies -XRecordWildCards"

tests:
  cooperstorage-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cooperstorage
